# Generated by Django 3.1.5 on 2021-01-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20210127_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['-created_t'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AddField(
            model_name='text',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
